### PR TITLE
Check current user status before promoting

### LINKED ISSUE #32: Onboarding flow demotes admins
The onboarding flow currently sets new members to full users without checking whether or not they're already a full user (or an admin)

### PR DESCRIPTION
**Pull request by jasonappah**
Closes #32

### CODE REVIEW

**Comment by MatthewStanciu** [comment]
Thanks for this! Quick question: is there a reason for the double `form`s? I'm reading through the part of the code and it's not clear to me why 2 instances of that have to be initialized. But I wanted to check that I'm not missing something.

**Comment by jasonappah** [comment]
I tried to use the same instance twice, and for the first request it worked fine, but the second request just seems to hang for some reason, but when I have them use 2 separate instances it works?? I'm not entirely sure why

**Comment by MatthewStanciu** [comment]
Oh weird

**Comment by MatthewStanciu** [comment]
Well you know the old saying: if it works it works. Don't think about the code just merge it

**Pull request merged**
